AWSTemplateFormatVersion: 2010-09-09
Description: |
  This template cretaes python flask
Parameters:
  KeyName:
    Description: Enter the name of your key
    Type: AWS::EC2::KeyPair::KeyName
    

  
Resources:
  WebServerSecGrp:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable HTTP fot Flask Weeb Server and SSH port to secure reach to my EC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80 
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  WebServerHost:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b5eea76982371e91
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroupIds:
        !Ref WebServerSecGrp
      UserDate:  !Base64 |
        #!/bin/bash
        yum update -y
        yum install python3 -y
        pip3 install flask
        cd /home/ec2-user
        wget https://raw.githubusercontent.com/bostantrt1/Project2/main/app.py
        mkdir templates
        cd templates
        wget https://raw.githubusercontent.com/bostantrt1/Project2/main/templates/index.html
        wget https://raw.githubusercontent.com/bostantrt1/Project2/main/templates/result.html
        cd ..
        python3 app.py

      Tags:
        - Key: Name
          Value: !Sub Web server of ${AWS::StackName} Stack
      
      
Outputs:
  WebsiteURL:
    Value: !Sub 
      -  http://{PublicAddress}
      -  PublicAddress :  !GetAtt  WebServerHost.PublicDnsName
    Description: Roman Numerals Converter App URL